2020-05-06 21:43:26,764 ERROR: Exception on /login [GET] [in /Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yanalazareva/Documents/myshop/myshop/app/routes.py", line 56, in login
    return render_template('login.html', title='Вход', form=form)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-05-06 21:43:52,154 INFO: Microblog startup [in /Users/yanalazareva/Documents/myshop/myshop/app/__init__.py:45]
2020-05-06 21:44:01,952 ERROR: Exception on /login [GET] [in /Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yanalazareva/Documents/myshop/myshop/app/routes.py", line 56, in login
    return render_template('login.html', title='Вход', form=form)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
