2020-05-07 09:17:28,276 ERROR: Exception on /catalog [GET] [in /Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yanalazareva/Documents/myshop/myshop/app/routes.py", line 32, in catalog
    return render_template('catalog.html', title='Каталог')
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/yanalazareva/Documents/mycinema/myvenv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/yanalazareva/Documents/myshop/myshop/app/templates/catalog.html", line 7, in template
    <img src="{{url_for('static', filename = 'bed2.jpg'}}" width="200" height="150" alt="bed"><br>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2020-05-07 09:18:32,916 INFO: Shop startup [in /Users/yanalazareva/Documents/myshop/myshop/app/__init__.py:48]
